version: 0.0.{build}
image: Ubuntu1804
environment:
  NPM_TOKEN:
    secure: CSzo9P7e9If8tU0CpcPKLr4wGqEvDvnsiJFw1+IoVdDUsKnPdXK+zan4xGV70d70
  GIT_AUTHOR_NAME: AppVeyor
  GIT_AUTHOR_EMAIL: build@redpoint.games
build_script:
- sh: yarn version --new-version $APPVEYOR_BUILD_VERSION
- sh: yarn build
test_script:
- sh: yarn test