version: 0.0.{build}
image: Ubuntu1804
environment:
  NPM_TOKEN:
    secure: CSzo9P7e9If8tU0CpcPKLr4wGqEvDvnsiJFw1+IoVdDUsKnPdXK+zan4xGV70d70
  GIT_AUTHOR_NAME: AppVeyor
  GIT_AUTHOR_EMAIL: build@redpoint.games
install:
- sh: yarn
before_build:
- sh: node --version
- sh: npm --version
build_script:
- sh: git config --global user.email "build@redpoint.games"
- sh: git config --global user.name "AppVeyor"
- sh: yarn version --new-version $APPVEYOR_BUILD_VERSION
- sh: yarn build
test_script:
- sh: yarn test
deploy_script:
- sh: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > $APPVEYOR_BUILD_FOLDER/.npmrc
  on:
    branch: master
- sh: npm pack
  on:
    branch: master
- sh: npm publish
  on:
    branch: master